import { useEffect, useMemo } from "react";
import { useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";

import { BRAND } from "../lib/brand";
import { getRemittancesApi } from "../lib/remittances/remittances";
import type { Remittance } from "../lib/remittances/types";

function money(cents?: number) {
  if (typeof cents !== "number") return "—";
  return `$${(cents / 100).toFixed(2)}`;
}

export function ProviderRemittancePrintPage() {
  const { id } = useParams();
  const remittanceId = id ?? "";

  const api = useMemo(() => getRemittancesApi(), []);

  const remittanceQuery = useQuery({
    queryKey: ["provider-remittance", remittanceId],
    enabled: !!remittanceId,
    queryFn: async () => {
      const all = (await api.list()) as Remittance[];
      return all.find((r) => r.id === remittanceId) ?? null;
    },
  });

  const remittance = remittanceQuery.data as Remittance | null | undefined;

  useEffect(() => {
    if (!remittance) return;
    const t = window.setTimeout(() => {
      window.print();
    }, 250);
    return () => window.clearTimeout(t);
  }, [remittance]);

  if (remittanceQuery.isLoading) {
    return <div className="container mx-auto px-4 py-10 text-sm text-muted-foreground">Loading…</div>;
  }

  if (!remittance) {
    return <div className="container mx-auto px-4 py-10 text-sm text-muted-foreground">Remittance not found.</div>;
  }

  return (
    <div className="min-h-screen bg-white text-slate-900">
      <div className="max-w-3xl mx-auto p-8">
        <div className="border rounded-xl overflow-hidden">
          <div className="px-6 py-5 border-b">
            <div className="flex items-start justify-between gap-6">
              <div>
                <div className="text-[11px] uppercase tracking-wide text-slate-500">{BRAND.name}</div>
                <h1 className="text-xl font-bold font-display mt-1">Remittance Report • Provider Copy</h1>
                <div className="text-sm text-slate-500 mt-1">
                  Remittances are submitted by dealers and reconciled by administrators.
                </div>
              </div>
              <div className="text-right">
                <div className="text-[11px] uppercase tracking-wide text-slate-500">Remittance #</div>
                <div className="text-sm font-semibold">{remittance.remittanceNumber}</div>
                <div className="text-[11px] text-slate-500 mt-1">Created {new Date(remittance.createdAt).toLocaleDateString()}</div>
              </div>
            </div>
          </div>

          <div className="px-6 py-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="rounded-lg border p-4">
                <div className="text-[11px] uppercase tracking-wide text-slate-500">Amount</div>
                <div className="text-lg font-semibold mt-1">{money(remittance.amountCents)}</div>
              </div>
              <div className="rounded-lg border p-4">
                <div className="text-[11px] uppercase tracking-wide text-slate-500">Status</div>
                <div className="text-lg font-semibold mt-1">{remittance.status === "PAID" ? "Paid" : "Due"}</div>
              </div>
              <div className="rounded-lg border p-4">
                <div className="text-[11px] uppercase tracking-wide text-slate-500">Last Updated</div>
                <div className="text-lg font-semibold mt-1">{new Date(remittance.updatedAt).toLocaleDateString()}</div>
              </div>
            </div>

            <div className="mt-6 rounded-lg border p-4">
              <div className="text-xs font-semibold uppercase tracking-wide text-slate-600">Read-only notice</div>
              <div className="mt-2 text-sm text-slate-600">
                Providers can download this report for support purposes. Remittances cannot be edited, approved, or reconciled in the Provider Portal.
              </div>
            </div>
          </div>

          <div className="px-6 py-4 border-t text-[11px] text-slate-500">Generated by {BRAND.name} • Provider read-only copy.</div>
        </div>
      </div>
    </div>
  );
}
