export type ContractStatusV2 = "draft" | "submitted" | "active" | "cancelled" | "expired";

export type ContractAddonSnapshot = {
  name: string;
  term: string;
  vehicleClass: string;
  dealerCost: number;
  retail: number;
  retailDisplay?: string;
  retailKey: string;
};

export type ContractV2 = {
  id: string;
  dealershipId: string;
  providerEntityId?: string;
  productId: string;
  createdBy?: string;
  customerFirstName: string;
  customerLastName: string;
  customerEmail?: string;
  customerPhone?: string;
  vehicleVin: string;
  vehicleMake: string;
  vehicleModel: string;
  vehicleYear: number;
  vehicleMileage?: number;
  contractPrice?: number;
  dealerCost?: number;
  pricingVehicleClass?: string;
  pricingTermMonths?: number;
  pricingTermKm?: number | null;
  pricingBasePriceCents?: number;
  pricingDealerCostCents?: number;
  addonSnapshot?: ContractAddonSnapshot[];
  addonTotalRetailCents?: number;
  addonTotalCostCents?: number;
  status: ContractStatusV2;
  startDate?: string;
  endDate?: string;
  createdAt: string;
  updatedAt: string;
};

export type CreateContractV2Input = {
  dealershipId: string;
  providerEntityId: string;
  productId: string;
  customerFirstName: string;
  customerLastName: string;
  customerEmail?: string;
  customerPhone?: string;
  vehicleVin: string;
  vehicleMake: string;
  vehicleModel: string;
  vehicleYear: number;
  vehicleMileage?: number;
  contractPrice?: number;
  dealerCost?: number;
  pricingVehicleClass?: string;
  pricingTermMonths?: number;
  pricingTermKm?: number | null;
  pricingBasePriceCents?: number;
  pricingDealerCostCents?: number;
  addonSnapshot?: ContractAddonSnapshot[];
  addonTotalRetailCents?: number;
  addonTotalCostCents?: number;
  startDate?: string;
  endDate?: string;
};
